library(tidyr)
library(shiny)
library(shinythemes)
library(shinyBS)
library(visNetwork)


ui <- fluidPage(
  tabsetPanel(selected = 1,
    tabPanel(title ="1. Introduction",
             value = 1,
             h1("Introduction to Trace Data"),
             p("When we think about ethnography, we might imagine a researcher observing how research subjects behave ",
               "\"in the field,\" away from a computer. ",
               "However, Geiger & Ribes (2011) suggest that we can also do ethnography on", strong("trace data"), 
               "such as the kinds of data produced by online platforms."),
             p("From Geiger and Ribes' paper, we might define three requirements of trace data and trace ethnography:"),
             p(em("1) The data are thin on their own but that become thick when used together.")),
             p(em("2) There are plentiful amounts of trace data produced in the research setting.")),
             p(em("3) These data \"are the primary mechanism in which users themselves know their distributed communities and act within them.\"")),
             br(),
             h2("Activity"),
             p("Looking at the 3 requirements listed above, which of these examples could be considered trace data? ",
               "Write 1-2 sentences for each response justifying your answer."),
             p("1. A series of tweets between a group of friends on Twitter"),
             p("2. The browser history on your phone or computer"),
             p("3. A single trail of footprints through a forest"),
             p("4. Github commit, pull request, and comment histories for an organization where developers ",
               "primarily communicate through Github"),
             p("5. Github commit, pull request, and comment histories for an organization where developers ",
               "primarily communicate in person"),
             p("6. The request, checkout, and return logs for the patrons of a library"),
             hr(),
             strong("References"),
             p("Geiger, R. S. & Ribes, D. (2011, January). Trace ethnography: Following coordination through documentary practices. ",
               "In 2011 44th Hawaii International Conference on System Sciences (pp. 1-10). IEEE.")
             
             ## TODO: make this activity a drag-and-drop plot with axes thick/thin data and ??
    ),
    tabPanel(title = "2. Handling Trace Data",
             value = 2,
             h1("Handling Trace Data"),
             p("There are many ways to work with trace data. Our research question and method will inform the perspective we choose. ",
               "This activity will explore several approaches for studying the same online research site."), 
             br(),
             h2("Activity"),
             p("For this activity, our research site will be the subreddit ", 
               a("r/books", href = "https://www.reddit.com/r/books/"), 
               ". For each step follow the instructions and then answer the questions below."),
             br(),
             h3("1. In Browser"),
             p("Let's start by simply examining the subreddit as it appears in our browser. Open another window or tab and visit the subreddit here: ", 
               a("https://www.reddit.com/r/books/top&t=all", href = "https://www.reddit.com/r/books/top&t=all"), 
               ". This URL will show you the top posts in the subreddit. ",
               "It may helpful to drill down into various elements, such as the comment section or individual user profiles."),
             p("To answer the questions below, it may be helpful to take a screenshot or download the page as a ",
               "PDF file that you can mark up."),
             br(),
             h4("Questions"),
             p("a. Where do you see trace data? If you have a screenshot or PDF available, you may indicate using circles or arrows. ",
               "Otherwise provide a list of items."),
             p("b. For the trace data elements you identified in (a), how thick or thin are the data? How might you interpret each ",
               "piece of data?"),
             br(),
             p("Latzko-Toth et al. give three suggestions on how to thicken trace data:"),
             p(em("i. conducting a trace interview")),
             p(em("ii. manually compiling trace data")),
             p(em("iii. performing ethnographic observations.")),
             p("By saving the subreddit page to your computer, you have already begun manually compiling trace data ",
               "(suggestion ii.)."),
             br(),
             p("c. How might you follow suggestions i. or iii. to thicken the data you collected? ",
               "Choose one suggestion and briefly describe a study design to accomplish this."),
             br(),
             h3("2. Tabular Format"),
             p("We can also reconstruct the data in a table using the Reddit API. ",
               "Using the API means that we are likely not interacting with the traces from the same perspective as the users; ",
               "however the API allows to quickly gather large amounts of data. The table below shows the 8 most upvoted posts in ",
               "r/books:"),
             dataTableOutput("rbooks_table"),
             br(),
             h4("Questions"),
             p("Recall the principles of trace ethnography from Geiger & Ribes' paper:"),
             p("From Geiger and Ribes' paper, we might define three requirements of trace data and trace ethnography:"),
             p(em("1) The data are thin on their own but that become thick when used together.")),
             p(em("2) There are plentiful amounts of trace data produced in the research setting.")),
             p(em("3) These data \"are the primary mechanism in which users themselves know their distributed communities ",
                  "and act within them.\"")),
             br(),
             p("a. For each principle, briefly state whether you think the tabular perspective fulfills the principle and ",
               "justify your answer."),
             br(),
             uiOutput("panel_style1"),
             bsCollapse(id = "thematic_coding_primer",
               bsCollapsePanel("Learn More: Thematic Coding Primer", 
                               p("Thematic coding involves qualitatively identifying themes in a data set. ",
                                 "While some information might be easy to analyze computationally (such as the year ",
                                 "the post was published or the number of upvotes), qualitative analysis helps us answer ",
                                 "questions that may be too nuanced or context-dependent for a computer. ",
                                 "For example, if we were interested in characterizing the kinds of posts in r/books, we might ",
                                 "try to categorize posts by emotion or by the kind of information they share."),
                               p("If you are unfamiliar with qualitative coding, you might think of trying to assign each post ",
                                 "to a category based on a common theme."),
                               style = "info"
               )
             ),
             p("b. Come up with 2-3 qualitative codes that you could apply to the data in the table and describe each one. ",
               "For example, you might code for whether the each of the top posts contains a breaking news story. "),
             br(),
             h3("3. Aggregate Metrics"),
             p("To get a high-level view, we could use descriptive statistics and visualizations. ",
               "For data scientists, this might be an especially familiar perspective."),
             br(),
             p("Here are some basic descriptive statistics about the top 50 posts:"),
             uiOutput("rbooks_ds"),
             br(),
             plotOutput("rbooks_plot"),
             br(),
             p("The plot above shows the number of upvotes versus the number of comments for the top 50 posts in r/books. ",
               "While it's hard to make any ethnographic observations from this perspective, such tools can help us find ",
               "interesting outliers or high-level patterns in the data that we can further examine qualitatively."),
             # br(),
             # h4("Questions"),
             # p("a. Do the descriptive statistics or plot prompt any insights that you might further explore qualitatively? Write a brief paragraph ",
             #   "describing any questions or hypotheses that you have."),
             br(),
             hr(),
             strong("References"),
             p("Geiger, R. S. & Ribes, D. (2011, January). Trace ethnography: Following coordination through documentary practices. ",
               "In 2011 44th Hawaii International Conference on System Sciences (pp. 1-10). IEEE."),
             p("Latzko-Toth, Guillaume, Claudine Bonneau, and Mélanie Millette. n.d. “Small Data, Thick Data.”
")
      
    ),
    tabPanel(title = "3. Mixing Methods",
             value = 3,
             h1("Mixing Methods"),
             p("In some cases, qualitative and quantitative methods can be used together in powerful ways. ",
               "For example, a qualitative perspective help us validate the assumptions we make in our data science work. ",
               "This activity will walk you through an example using a network visualization."),
             br(),
             h2("Activity"),
             p("Suppose we were interested in how community guidelines are enforced by moderators on Reddit. ",
               "We might make the assumption that, if the same person moderates two subreddits, ",
               "the two subreddits will have more similar community norms. ",
               "We can build on this assumption by making a ", em("shared moderator"), "network ",
               "where two subreddits are connected if they share a moderator. ",
               "In this case, the vertices of our network are the 100 most popular subreddits.",
               "connected by shared moderator relationships are edges. "),
             p("In the network visualization below, the small squares represent vertices (i.e. subreddits) ",
               "and the lines between them represent edges (moderators).", 
               "Two subreddits will be closer together if they are pulled together by an edge. ",
               "Otherwise they will drift away from each other. 
               To help visually distinguish between different areas of the network, each vertex is ",
               "colored according to the results of a Louvain clustering algorithm."),
             br(),
             sidebarLayout(
               sidebarPanel(
                 textInput(inputId = "exclude_labels", placeholder = "Moderator1, moderator2, ...", label = "Exclude edges from network (case-sensitive):"),
                 dataTableOutput("moderator_table")
               ),
               mainPanel(
                 visNetworkOutput("network", height = "600px", width = "auto"),
               )
             ),
             br(),
             uiOutput("panel_style2"),
             bsCollapse(id = "understanding_network_proj",
               bsCollapsePanel("Learn More: Understanding Network Projections",
                 p("This network is defined by ", em("shared moderator"), " ties, meaning two vertices are connected if ",
                   "they share a moderator. Another way to describe this network is as a projection of the ", em("subreddit-moderator"),
                   " network. Here's a quick example to illustrate what a network projection is."),
                 fluidRow(
                   splitLayout(
                     cellWidths = c("75%", "25%"), 
                     div(
                       h4("Example"),
                       p("Suppose we were studying cat owners on Reddit and were interested in the ",
                         "shared moderator network between cat-related subreddits and had pulled the following data ",
                         "using the Reddit API. The table on the right shows who moderates which subreddit. ",
                         "We can see that some users moderate multiple subreddits; for example, user catdad67 moderates ",
                         "r/cat_toys, r/cat_videos, and r/kittens."),
                       p("Another way to represent the relational data in the table is with network visualizations. ", strong("Figure A"),
                         "shows us the same information as the table above: subreddits (blue circles) are connected to ",
                         "users who moderate them (orange squares). We can call this a subreddit-moderator network."),
                       p("While the subreddit-moderator network might be the most intuitive way to represent ",
                         "the subreddit-moderator relationships, it poses an analytical challenge because it is a ",
                         "bimodal network, meaning that vertices in the network represent two different things ",
                         "(subreddits and users). We may instead wish to ", em("project"), " or collapse the network ",
                         "into subreddit space (vertices only represent subreddits) or moderator space (vertices only ",
                         "represent moderators).")
                     ),
                     tableOutput("ex_tab"),
                     cellArgs = list(style='white-space: normal; padding: 10px;')
                   )
                 ),
                 p(strong("Figure B"), " and ", strong("Figure C"), " illustrate projecting the subreddit-moderator network ",
                   "shown in ", strong("Figure A"), " into a shared moderator network. We start by drawing an edge between any ",
                   "two subreddits who share a moderator (", strong("Figure B"), "). ",
                   "For example, r/cat_toys, r/cat_videos, and r/kittens are all connected to each other because they are ",
                   "moderated by u/catdad67. We can then remove the vertices representing moderators and the original edges ",
                   "(", strong("Figure C"), ")."),
                 fluidRow(
                   splitLayout(
                     cellWidths = rep("33%", 3),
                     plotOutput("ex_orig", height = "350px", width = "350px"),
                     plotOutput("ex_comb", height = "350px", width = "350px"),
                     plotOutput("ex_proj", height = "350px", width = "350px"),
                   )
                 ),
                 p("As you can see, the density of shared moderator network (amount of edges) can increase exponentially ",
                   "relative to the number of ties in the original subreddit-moderator network."),
                 style = "info"
               )
             ),
             br(),
             
             h3("Questions"),
             p("a. At first glance, how would you describe the network? How do you interpret what you see?"),
             br(),
             p("The table on the left shows you which moderator has the greatest number of edges in the network. ",
               "Remember that ", em("n"), " represents how many pairs of subreddits are connected by this moderator, ",
               em("not"), " the number of subreddits moderated by this user."),
             br(),
             p("We can see from the table that one account is responsible for more than half of the edges. ",
               "Take a moment to visit ", 
               a("AutoModerator's user page", href = "https://www.reddit.com/user/automoderator"), " here."),
             br(),
             p("b. Who (or what) is AutoModerator?"),
             br(),
             p("c. We made the assumption that if two subreddits shared a moderator they would likely ",
               "share values and norms. After visiting AutoModerator's user page, do you think this assumption ",
               "holds up?"),
             br(),
             p("Type \"AutoModerator\" into the text box to hide AutoModerator's edges."),
             p("d. Describe the network after hiding Automoderator's edges and compare this description to ",
               "your answer for Question (a). How does this change your interpretation?"),
             p("e. How did looking at Automoderator's account change your understanding of the data? ",
               "Write a brief paragraph describing how you might use trace ethnography to validate or inform ",
               "the assumptions of our shared moderator network."),
             hr(),
             strong("Notes"),
             p("Data collected using the PRAW API on July 7th, 2023.")
    ),
    tabPanel(title = "4. Reflection",
             value = 4,
             h1("Reflection"),
             p("a. Reflecting on what you learned about trace ethnography, what makes a perspective \"ethnographic\"?"),
             p("b. Could you use trace ethnography in your own work? Why or why not?"),
             p("c. Can you do trace ethnography on a dataset that's already been cleaned or preprocessed? Why or why not?")
    )
  ),
  theme = shinytheme("lumen")
)